name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  workflows-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1.7.9

  qa:
    needs: workflows-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7

      - name: Ruff check
        run: uv run --only-group lint ruff check

      - name: Ruff format
        run: uv run --only-group lint ruff format --check

      - name: Ty check
        run: uv run --group qa ty check --output-format=github


  test:
    needs: qa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - name: Run tests with coverage
        run: uv run --group test -p ${{ matrix.python-version }} pytest
